# Generated by Django 5.1.2 on 2024-10-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PizzaOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pizza_type",
                    models.CharField(
                        choices=[
                            ("Vegetarian", "Vegetarian"),
                            ("Pepperoni", "Pepperoni"),
                            ("Roman Pizza", "Roman Pizza"),
                            ("Sicilian", "Sicilian"),
                            ("Hawaiian", "Hawaiian"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
            ],
        ),
    ]
